# This is a basic workflow to help you get started with Actions

name: Package Game and create a new release

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  create_new_release_tag:
      runs-on: ubuntu-latest
      outputs:
        previous-tag: ${{ steps.previoustag.outputs.tag }}
        new-tag: ${{ steps.semvers.outputs.patch }}
      steps:
        - uses: actions/checkout@v2.2.0
          with:
            fetch-depth: 0
        - name: 'Get Previous tag'
          id: previoustag
          uses: "WyriHaximus/github-action-get-previous-tag@v1.0.1"

        - name: 'Get next minor version'
          id: semvers
          uses: "WyriHaximus/github-action-next-semvers@v1"
          with:
            version: ${{ steps.previoustag.outputs.tag }}
            
        - name: Display old version
          run: echo ${{ steps.previoustag.outputs.tag }}
          
        - name: Display new version
          run: echo ${{ steps.semvers.outputs.patch }}


  buildForAllSupportedPlatformsAndRelease:
    name: Build for ${{ matrix.targetPlatform }}
    needs: create_new_release_tag
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
        projectPath:
          - unity-project-with-correct-tests
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
             
      - name: Display outputs from previous job ğŸ”
        run: |
          echo ${{ needs.create_new_release_tag.outputs.previous-tag }}
          echo ${{ needs.create_new_release_tag.outputs.new-tag }}
           
      - name: Build game ğŸ® ğŸ“¦
        uses: game-ci/unity-builder@v2
        with:
          buildName: hexxle_game-${{ matrix.targetPlatform }}-${{ needs.create_new_release_tag.outputs.new-tag }}
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: ${{ matrix.projectPath }}
        
      - name: Display filestructure for debugging ğŸ”
        run: |
          ls -lah
          cd build
          ls -lah
          cd ${{ matrix.targetPlatform }}
          ls -lah
      
      - name: Create a compressed directory of the build ğŸ“
        run: tar -czvf hexxle_game-${{ matrix.targetPlatform }}-${{ needs.create_new_release_tag.outputs.new-tag }}.tar.gz /build/${{ matrix.targetPlatform }}
          
      - name: Display filestructure again for debugging ğŸ”
        run: |
          ls -lah
          cd build
          ls -lah
          cd ${{ matrix.targetPlatform }}
          ls -lah
      
      - name: Release game! ğŸš€
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_new_release_tag.outputs.new-tag }}
          files: hexxle_game-${{ matrix.targetPlatform }}-${{ needs.create_new_release_tag.outputs.new-tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE_TOKEN }}
